
[34m[1mwandb[39m[22m: [33mWARNING[39m Serializing object of type ndarray that is 786576 bytes
training new model, the num of training epochs is 3
The num of num_steps_per_level 24
The num of num_steps_per_epoch 240
  0%|                                                                                                                                             | 0/3 [00:00<?, ?it/s]
the shape of batch_data: (14, 384, 512, 6)
the shape of batch_data after transformation (10, 5, 384, 512, 6)
The shape of input: (10, 384, 512, 6)
The shape of x_input (10, 384, 512, 6) and the shape of f_cori_uv (10, 384, 512, 2)
  0%|                                                                                                                                             | 0/3 [02:35<?, ?it/s]
Traceback (most recent call last):
  File "/work/09012/haoli1/ls6/hurricane/code/hurr_u_net_2d0.0.py", line 111, in <module>
    trainer.train_model(Train_data, Test_data, num_epochs=num_epochs)
  File "/work/09012/haoli1/ls6/hurricane/code/Train_mod_2d.py", line 253, in train_model
    rel_err_u, rel_err_v, rel_rr_d, rel_err_p, err_test = self.eval_model(self.state, test_data)
  File "/work/09012/haoli1/ls6/JAX/lib/python3.9/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/work/09012/haoli1/ls6/JAX/lib/python3.9/site-packages/jax/_src/api.py", line 620, in cache_miss
    execute = dispatch._xla_call_impl_lazy(fun_, *tracers, **params)
  File "/work/09012/haoli1/ls6/JAX/lib/python3.9/site-packages/jax/_src/dispatch.py", line 236, in _xla_call_impl_lazy
    return xla_callable(fun, device, backend, name, donated_invars, keep_unused,
  File "/work/09012/haoli1/ls6/JAX/lib/python3.9/site-packages/jax/linear_util.py", line 300, in memoized_fun
    ans = call(fun, *args)
  File "/work/09012/haoli1/ls6/JAX/lib/python3.9/site-packages/jax/_src/dispatch.py", line 359, in _xla_callable_uncached
    return lower_xla_callable(fun, device, backend, name, donated_invars, False,
  File "/work/09012/haoli1/ls6/JAX/lib/python3.9/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
  File "/work/09012/haoli1/ls6/JAX/lib/python3.9/site-packages/jax/_src/dispatch.py", line 445, in lower_xla_callable
    jaxpr, out_type, consts = pe.trace_to_jaxpr_final2(
  File "/work/09012/haoli1/ls6/JAX/lib/python3.9/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
  File "/work/09012/haoli1/ls6/JAX/lib/python3.9/site-packages/jax/interpreters/partial_eval.py", line 2081, in trace_to_jaxpr_final2
    jaxpr, out_type, consts = trace_to_subjaxpr_dynamic2(fun, main, debug_info)
  File "/work/09012/haoli1/ls6/JAX/lib/python3.9/site-packages/jax/interpreters/partial_eval.py", line 2031, in trace_to_subjaxpr_dynamic2
    ans = fun.call_wrapped(*in_tracers_)
  File "/work/09012/haoli1/ls6/JAX/lib/python3.9/site-packages/jax/linear_util.py", line 167, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/work/09012/haoli1/ls6/hurricane/code/Train_mod_2d.py", line 178, in eval_model
    N, H, W, C = test_data.shape
jax._src.traceback_util.UnfilteredStackTrace: ValueError: too many values to unpack (expected 4)
The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.
--------------------
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/work/09012/haoli1/ls6/hurricane/code/hurr_u_net_2d0.0.py", line 111, in <module>
    trainer.train_model(Train_data, Test_data, num_epochs=num_epochs)
  File "/work/09012/haoli1/ls6/hurricane/code/Train_mod_2d.py", line 253, in train_model
    rel_err_u, rel_err_v, rel_rr_d, rel_err_p, err_test = self.eval_model(self.state, test_data)
  File "/work/09012/haoli1/ls6/hurricane/code/Train_mod_2d.py", line 178, in eval_model
    N, H, W, C = test_data.shape
ValueError: too many values to unpack (expected 4)